language: node_js

node_js: 
  - "8"

cache:
  directories:
    - node_modules

before_install:
  - "npm i"

after_script:
  - npm run build
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "travis building"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master

env:
 global: